### ISSUE TITLE
pidcat seems not work now

### ISSUE THREAD

**Issue by wispy316** [nisrulz/android-tips-tricks#13] opened 2017-03-31 09:30 UTC
just as https://github.com/JakeWharton/pidcat says.

do  _brew install pidcat_  , then _pidcat com.xxx.xxx_ .
but Nothing occur.

Did your pidcat works now?
My environment  is MacPro with newest android_sdk.

**Comment by ZahidRasheed** [comment] 2017-07-14 14:11
Mine works with MacPro and newest android_sdk. Just make sure you are using the correct package name otherwise just use  pidcat --current for whatever you have just compiled.

**Comment by nisrulz** [comment] 2017-10-11 04:09
@wispy316 Did you figure out a way to get it to work for you? I have ran it on my side and the flow exactly the same as mentioned in the repo.

Please close this issue after commenting your solution if it was different or just otherwise.
Thank you

**Comment by nisrulz** [comment] 2018-09-02 20:02
Closing since no response. Considering it is working as intended.

**Closed as completed by nisrulz** 2018-09-02 20:02 UTC
